### ISSUE TITLE
Last 30/90 days evaluation for CAMS2_83

### ISSUE THREAD

**Issue by heikoklein** [metno/pyaro-readers#33]
Data-Analyzers of CAMS2_83 would like to have the results of the current season, i.e. last 30 days or last 90 days on the web-page.
Results of the last 30 or 90 days should be regularly produced, if possible.

**Comment by charlienegri** [comment]
jobs for the "current season" evaluations have been added to the aerocom ecflow suite https://gitlab.met.no/met/fou/kl/ecflowsuite-aerocom/-/tree/main/cams2_83/job?ref_type=heads and are up and running since april 9, the results are pushed to aeroval, hidden for the moment,   
Michael will talk to ECWMF to see if the "current season or last 30 days if we are less than 30 days into a season" strategy is approved and then we will tweak as neede and make them public

**Comment by charlienegri** [comment]
the results are published: 
https://cams2-83.aeroval.met.no/pages/evaluation/?project=cams2-83&experiment=forecast-current-season&tab=median&station=ALL 
https://cams2-83.aeroval.met.no/pages/evaluation/?project=cams2-83&experiment=analysis-current-season&tab=median&station=ALL  
there might be need for some tweaks
